services:
  # MATS broker microservice
  nats-server:
    container_name: nats-server
    image: nats:alpine3.20
    ports:
      - 8222:8222 # Clients management (Public port)
      # - 4222:4222 # Client port (Not necessary for current Network)
      # - 6222:6222 # Routing port for clustering (Not necessary for current Network)

  # Client gateway microservice
  client-gateway:
    container_name: client-gateway
    build:
      context: ./client-gateway
      dockerfile: Dockerfile
    ports:
      - ${CLIENT_GATEWAY_PORT}:3000 # Local:Container
    volumes:
      - ./client-gateway/src:/usr/src/app/src # Binding container to Node JS filesystem
    command: yarn run start:dev
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222 # Docker nats-server DNS
    depends_on:
      - nats-server

  # Products microservice
  products-ms:
    container_name: products-ms
    build:
      context: ./products-ms
      dockerfile: Dockerfile
    volumes:
      - ./products-ms/src:/usr/src/app/src # Binding container to Node JS filesystem
    command: yarn run start:docker
    environment:
      - PORT=3001
      - NATS_SERVERS=nats://nats-server:4222 # Docker nats-server DNS
      - DATABASE_URL=file:./dev.db # SQLite temporal database
    depends_on:
      - nats-server

  # Orders microservice
  orders-ms:
    container_name: orders-ms
    build:
      context: ./orders-ms
      dockerfile: Dockerfile
    volumes:
      - ./orders-ms/src:/usr/src/app/src # Binding container to Node JS filesystem
    command: yarn run start:docker
    environment:
      - PORT=3002
      - NATS_SERVERS=nats://nats-server:4222 # Docker nats-server DNS
      - DATABASE_URL=postgresql://postgres:123456@orders-db:5432/ordersms?schema=public
    depends_on:
      - orders-db
      - nats-server

  # Extends orders db from other docker-compose config file
  # orders-db:
  #   extends:
  #     file: ./orders-ms/docker-compose.yml
  #     service: orders-db

  # Local postgres orders Postgres database
  orders-db:
    container_name: orders_database
    image: postgres:15-alpine
    volumes:
      - ./orders-ms/postgres:/var/lib/postgresql/data
    ports: # Private network DB
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=ordersms
